sudo: false
language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6

branches:
  only:
    - master
    - develop

before_install: gem install bundler

before_script:
  - bundle exec rake checkpoint:migrate
  - bundle exec rake keycard:migrate

script:
    - bundle exec rspec

matrix:
  include:
    - rvm: ruby-head
      script: bin/rubocop

