sudo: false
language: ruby
services:
  - docker
rvm:
  - 2.4
  - 2.5
  - 2.6

branches:
  only:
    - master
    - develop

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - bundle exec rake checkpoint:migrate
  - bundle exec rake keycard:migrate

script:
    - bundle exec rspec
    - bundle exec cucumber
    - docker-compose run dev bin/rspec

matrix:
  include:
    - rvm: ruby-head
      script: bundle exec rubocop

