version: '3.7'
services:
  dev:
    build:
      context: .
      target: base
    command: ["bundle", "exec", "rspec"]
    volumes:
      - type: bind
        source: '.'
        target: '/usr/src/app'
  app:
    build: .
    command: ["bin/rails", "server"]

