# configuration for upload paths

production:

development:
  upload_path: /tmp/incoming
  rsync_point: localhost:incoming

test:
  # application-writable directory where upload points should be created, e.g. /pfdr/incoming/uniqname
  upload_path: /tmp/pfdr/incoming/
  # rsync point to user-writable upload path
  rsync_point: localhost:incoming
  # application-writable directory for final storage of bags; allows creation of dirs, files
  storage_path: /tmp/pfdr/storage/
