# configuration for upload paths

production:

development:
  external:
    audio: "/path/to/validator"
    video: "/path/to/validator"
  bagger_profile:
    digital: "http://uri_to_bagger_profile"

test:
  external:
    audio: "/path/to/validator"
    video: "/path/to/validator"
  bagger_profile:
    digital: "/path/to/profile"
