upload:
  upload_path: data/incoming
  rsync_point: localhost:incoming
  storage_path: data/storage
validation:
  external:
    audio: "bin/validate_audio.sh"
    video: "bin/validate_video.pl"
  bagger_profile:
    digital: "http://uri_to_bagger_profile"
checkpoint:
  database: 
    adapter: sqlite
    database: db/checkpoint_dev.sqlite3
keycard:
  database: 
    adapter: sqlite
    database: db/keycard_dev.sqlite3
