allow_impersonation: true

# One day in development
session_timeout: 86400

upload:
  upload_path: data/incoming
  rsync_point: localhost:incoming
  storage_path: data/storage
validation:
  external:
    audio: "bin/validate_audio.sh"
    bentleyaudio: "bin/validate_bentleyaudio.sh"
    video: "bin/validate_video.pl"
  bagger_profile:
    digital: "config/profiles/digital-profile.json"
    video_game: "config/profiles/video-game-profile.json"
checkpoint:
  database: 
    adapter: sqlite
    database: db/checkpoint_dev.sqlite3
keycard:
  database: 
    adapter: sqlite
    database: db/keycard_dev.sqlite3
