upload:
  upload_path: /tmp/incoming
  rsync_point: localhost:incoming
  storage_path: /tmp/pfdr/storage/
validation:
  external:
    audio: "bin/validate_audio.sh"
    video: "bin/validate_video.pl"
  bagger_profile:
    digital: "http://uri_to_bagger_profile"


