upload:
  upload_path: /tmp/pfdr/incoming/
  rsync_point: localhost:incoming
  storage_path: /tmp/pfdr/storage/
validation:
  external:
    audio: "/path/to/validator"
    video: "/path/to/validator"
  bagger_profile:
    digital: "/path/to/profile"

